name: Build Release App Bundle

on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build APK
        run: ./gradlew app:assembleRelease
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Rename
        run: mv app/build/outputs/apk/release/app-release-unsigned-signed.apk VolumeKeyMusicManagerModule-release.apk
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: VolumeKeyMusicManagerModule-release.apk
